FROM node:14

# Set working directory
WORKDIR /var/www/html

# Copy existing application directory contents
COPY . .

# Install Node.js dependencies
RUN npm install

# Build assets
RUN npm run prod

COPY . .