version: "3"

networks:
  laravel:

volumes:
  mundolector_db:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    container_name: mundolector_nginx
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mundolector_php
    environment:
      TZ: America/Bogota
    depends_on:
      - node
    ports:
      - 9000
    networks:
      - laravel

