version: "3"
networks:
  clubdelbuho:
  dokploy-network:
    external: true
    
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80
    container_name: mundolector_nginx
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - dokploy-network
      - clubdelbuho
    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.rule=Host(`${APP_HOST}`)
      - traefik.http.routers.${HASH}.entrypoints=websecure
      - traefik.http.routers.${HASH}.tls.certResolver=letsencrypt
      - traefik.http.services.${HASH}.loadbalancer.server.port=80

  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production
    container_name: mundolector_php
    environment:
      TZ: America/Bogota
    volumes:
      - .:/var/www/html
      # - ./php/php.ini:/etc/php7.4/fpm/php.ini
      - ./php/php.ini:/usr/local/etc/php.ini
      - ./php/www.conf:/etc/php7.4/fpm/pool.d/www.conf
    networks:
      - clubdelbuho
      - dokploy-network